language: ruby
cache: bundler

os:
  - linux
  - osx

rvm:
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - ruby-head
  - rbx-2

addons:
  apt:
    packages:
    - cmake
    - libssh2-1-dev
    - openssh-client
    - openssh-server

sudo: required

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head

git:
  submodules: false

before_install:
  - git submodule update --init
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./vendor/libgit2/script/install-deps-osx.sh; fi

script: script/travisbuild
